Traceback (most recent call last):
  File "C:/Users/kumar/PycharmProjects/Debuging/traceback_exception.py", line 8, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
